### ISSUE TITLE
"Factories are themselves polymorphic" example

### ISSUE THREAD

**Issue by andreapier** [grzesiek-galezowski/tdd-ebook#117]
Hello, Thanks for your ebook, I find it very very good!
I wanted to ask a question about the chapter "Factories are themselves polymorphic".
In the example you mention that version 2 of the protocol was about removing flags and allowing the factory to handle cases when a single message is used to signal 2 conditions (eg: `IsSessionInit(), IsSessionEnd()`). However, looking at the `Version2ProtocolMessageFactory` I cannot see where such a condition is implemented.
Is the example incomplete (that would still be ok, just want to be sure I am not missing something)?

**Comment by grzesiek-galezowski** [comment]
Hi, I just went through this example and it seems the wording is unfortunate. It should've said something like "Imagine we decided that having so many separate flags is too cumbersome as with such a design, we risk receiving a message where two or more flags are set to true (e.g. someone might send a message that indicates that it's both a session initialization and a session end). Supporting such cases (e.g. by validating and rejecting such messages) requires additional effort".

The point was that when each message type is a question, we risk being passed a message where both IsSessionInit() and IsSessionEnd() return true, which is against our assumptions. Please let me know of the proposed wording explains it better (or propose an alternative version) so that I can improve this paragraph.

**Comment by andreapier** [comment]
Hi, thanks for the clarification.
I'd say that this new wording makes it much easier (at least for me) to get the meaning.
Thanks for taking the time to address my question!

**Comment by grzesiek-galezowski** [comment]
Cool, I'll push a change today and regenerate the book. Thank you for helping me make the book better!

**Comment by grzesiek-galezowski** [comment]
The new version is available on the leanpub page with the fix.
